services:
  db:
    image: postgres:latest
    container_name: local-postgres-fast-campus
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fastcampus_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: